### PR TITLE
remove useless code

### PR DESCRIPTION
**Pull request by plucury**
The line `self._wait` seems never be used

### CODE REVIEW

**Comment by kcbsbo** [comment]
I guess self.wait unused temporary , will be in use later.

and I want to know how you guys to see the results in your Futures object

**Comment by plucury** [comment]
It‘s shortcut for `self._future.result`. However he used `self._future.result` but `self._wait` in the following code.

**Comment by madisonmay** [comment]
The use case of `self._wait` is the following:

```
@threads(10):
def user_defined_function():
    # code that causes side effects
    return 

future = user_defined_function()
future._wait()
```

Now you don't care about the return value of this function(`None` in this case), and will likely never access the value of the function return.  How do you cause the function to block when you need it to?  You call `future._wait()` to ensure that the function has completed before writing code that relies on the function's side effects.

Still need to think of a good way to explain and document that feature, but that's the motivation for that alias.

**Comment by plucury** [comment]
@madisonmay Thanks for your explain. But with the code above, people need to config timeout again.
How about make `_wait` method like this?

```
def _wait(self):
    self._future.result(self._timeout)
```

**Comment by madisonmay** [comment]
Excellent suggestion, I'll push a fix!  Thanks, @plucury.

**Comment by plucury** [comment]
@madisonmay Just updated the PR. Please review.

**Comment by madisonmay** [comment]
Sorry it took me so long to get around to this, the PR looks great.  Merging it in now.

**Pull request merged**
